### ISSUE TITLE
Make the repo name more exciting!

### ISSUE THREAD

**Issue by cjbe** [OxfordIonTrapGroup/atomic_physics#26]
"ion_phys" feels a little derivative, and more importantly inaccurate as this repo does not model anything special about ions, but is more generally about atomic physics.

That said, how about calling it "atomic"? (better suggestions welcome!)

**Comment by hartytp** [comment]
Yeah, it's not a great name. As @dnadlinger has already pointed out, `atomic` is taken on PyPI.

FWIW, the reason I went for `ion_phys` rather than general atomic physics is: while this is just basic atomic physics, it's definitely tailored towards solving the types of problems that ion trappers face. My general knowledge of AMO beyond ion traps isn't as broad as it could be, but it wasn't clear to me how widely useful this package would be and I didn't want to give misleading impressions about which domains this package would work ergonomically in. If someone with a better understanding of the needs of other parts of the community can reassure me that this will work well in other domains then I'll be happy...

**Comment by cjbe** [comment]
There is nothing ion specific - rate equations etc are just as useful for people with a full complement of electrons

**Comment by hartytp** [comment]
And the quantum numbers we use in `Level` for multi-electron atoms?

**Comment by cjbe** [comment]
thats not an ion vs atom thing: single valence electron atoms (Li, Na, K, Rb, Cs) are pretty commonly used...

**Comment by RHanley1** [comment]
Would still be valid of the alkali-metal atoms..

**Comment by hartytp** [comment]
Yeah, true. You're right, the conditions are really just single-electron in the JLS coupling regime. Other than that, I think it's maximally general. We should articulate that though (as I think dealing with other coupling regimes would be outside the scope of this package forever).

**Comment by RHanley1** [comment]
I think it would be reasonably easy to add in two-electron atoms too if one wanted to (not that I do), as the only complication which arises would be on intercombination lines where you'd have to deal with spin changes in the matrix elements. So I think the package is applicable in a wide variety of cases.

**Comment by hartytp** [comment]
Maybe you're right. It just could get a little messy (e.g. we'd need multiple `Level` `namedtuple`s)

**Comment by hartytp** [comment]
`atomic_phys`? Not exciting but more accurate...
