### ISSUE TITLE
Symbols: PEP8, avoid overly short names

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/atomic_physics#30]
To help cement the status of this as the default way of doing ion-related calculations, it would be good to stick with the default way of doing things – e.g., pick a style guide, and stick to it. For instance, `setB` doesn't follow the `snake_case` convention used in other parts of the code. In Python, PEP8 has pretty close to official status, so it might be a good idea to stick to that.

It is probably also a good idea to prefer slightly longer, but self-documenting names, e.g. `saturation_intensity` instead of `I0`.

**Comment by hartytp** [comment]
> To help cement the status of this as the default way of doing ion-related calculations, it would be good to stick with the default way of doing things – e.g., pick a style guide, and stick to it. For instance, setB doesn't follow the snake_case convention used in other parts of the code. In Python, PEP8 has pretty close to official status, so it might be a good idea to stick to that.

Yes. We should pick a formatter that's a little more opinionated than flake8 and stick to it.

> It is probably also a good idea to prefer slightly longer, but self-documenting names, e.g. saturation_intensity instead of I0.

This I have more mixed feelings about. I find that in physics-type code there are plenty of places where the short variable names lints make the code less readable. e.g. will we replace `B` with `magnetic_field`? I really don't like it where code starts to span over multiple lines because of insistence on minimum sizes on variable names.

**Comment by cjbe** [comment]
>> It is probably also a good idea to prefer slightly longer, but self-documenting names, e.g. saturation_intensity instead of I0.

>This I have more mixed feelings about. I find that in physics-type code there are plenty of places where the short variable names lints make the code less readable. e.g. will we replace B with magnetic_field? I really don't like it where code starts to span over multiple lines because of insistence on minimum sizes on variable names.

Sure - it is a tiny bit more effort to write, but is invaluable for reading the code, and people will spend more time reading / understanding the code than writing it, so I fully agree with @dnadlinger here

**Comment by hartytp** [comment]
TBH I'm not even convinced that `saturation_intensity` is always more readable than `I0` in this kind of code. Personally, I'd prefer one line of maths with `I0` to multiple lines with `saturation_intensity`.

**Comment by cjbe** [comment]
`I0` may make sense to you, but it did not to me when I read this code earlier on today - my first guess was something to do with the nuclear spin

**Comment by hartytp** [comment]
It's not about being more effort to write as about readability. Do you really feel that `magnetic_field` is better than `B`? Do you really want to parse multiple lines of code to enforce that? For me it would be a definite step back.

**Comment by hartytp** [comment]
I find that when one starts combining python indentation (e.g. a couple of `for` loops or a nested function) with long variable names you find that it becomes hard to express any mathematical expression without it spilling onto lots of lines and becoming a mess.

**Comment by cjbe** [comment]
That is my point too - it is always obvious when you are in the trenches writing this code what things mean. The acid test is how readable this is for people who did not write the code. Again, as @dnadlinger pointed out, there is a well developed strategy for managing this holistically, which points towards more descriptive names being better over the whole lifecycle.

**Comment by hartytp** [comment]
In many cases I agree with that and I have made an effort to avoid non-descriptive names in the code-base. However, there are a small number of cases where there are variable names that have a close correspondence with the physics. e.g. they match the variables used in the physics docs.

I don't think this is a principle that works in this kind of code if applied blindly. So, we can't use `Gamma` for scattering amplitudes. We can't use `delta` for detunings. I think that if we tried to do all that then we'd end up with something so verbose that it became unreadable.

Anyway, rather than discussing this theoretically it's best to look at a PR and see what it does to the code.

Consistent function naming (including snake case) I'm happy to implement myself at some point soon. The rest I'll leave for someone else.

**Comment by hartytp** [comment]
Do our Hamiltonians in the code end up looking like `nuclear_g_factor*nuclear_magneton*magnetic_field*nuclear_magnetic_moment_z` rather than `gI*_uN*B*Iz` etc? Particularly when the latter can be easily read off from the physics documents that go with the code? I certainly find the former harder to proof read and check for consistency with the physics.

That doesn't mean that I think that one shouldn't worry about non-descriptive names, just that it's one of those rules that should be applied on a case-by-case basis.

**Comment by dnadlinger** [comment]
> Yes. We should pick a formatter that's a little more opinionated than flake8 and stick to it.

I find that in practice the main benefit is not even formatters being opinionated – it's fine if the settings reflect the opinions of the maintainers or the prevalent style in the project (though, of course, a somewhat standard choice makes it easier on the eyes for casual contributors). The value comes from just having automated way to format code at the press of a button, and not having to worry about this when typing code (or applying automatic refactorings). 

I can recommend YAPF, as we have been using this for other projects in the group; see #31.

**Comment by hartytp** [comment]
Yep, that's fine. I'll have a look at the YAPF settings when I have time and find something I'm happy with.

**Comment by hartytp** [comment]
> Sure - it is a tiny bit more effort to write, but is invaluable for reading the code, and people will spend more time reading / understanding the code than writing it, so I fully agree with @dnadlinger here

Okay, I agree! I haven't had time to do this yet so I've told flake8 to ignore short names, but I would gladly merge a PR that resolves this

**Comment by hartytp** [comment]
Thanks for flagging @dnadlinger @cjbe . As part of the v1.1 release, I've taken a more coherent view to variable naming. See https://oxfordiontrapgroup.github.io/atomic_physics/definitions_and_conventions.html#variable-names for details, but my policy is essentially "standard quantum numbers are okay to have short names, but everything else gets a fully descriptive name". LMK if you have concerns (e.g. if you'd like to advocate strongly for "n" -> "principal_quantum_number" etc)
