### ISSUE TITLE
Clean up API

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/atomic_physics#38]
> Out of interest, why is this not a proper solution? I couldn't find a way of comparing a number with a slice object without explicitly breaking it apart.

The current design essentially assumes that the start/stop indices are private to a LevelData. This method works around that in a really ugly way, suggesting that the interface is not great. There are a few potentially better solutions: move this functionality into `LevelData`, make the start/stop indices public interface, etc

As I said above, I also suspect that testing if the state is in the range is needlessly slow compared with a simple bounds check (state >= start and state < stop). in this instance the speed is probably not particularly relevant but if one gets in the habit of making everything needlessly slow then the optimization etc can become really painful. I've tried to design everything to be decently efficient.

_Originally posted by @hartytp in https://github.com/OxfordIonTrapGroup/ion_phys/issues/34#issuecomment-694083695_

**Comment by hartytp** [comment]
We should also convert the named tuples to data classes (frozen to make them hashable so we can keep using them as dictionary keys).

**Comment by hartytp** [comment]
A lot of what's nasty about the level data is that we pass them into the atom constructor. That's a bit nasty because we end up with partially-constructed objects, since the level data can't be constructed until we know all the levels and can sort them.

A better design here would be to make this a frozen data class. Pass a list of levels into the atom constructor and then construct the level data objects inside the constructor.
